/*USANDO EL PAQUETE YARGS NOS FACILITA LAS COSAS PARA RECOGER INFORMACION 
DESDE LA CONSOLA DE COMANDO POR MEDIO DE PALABRAS RESERVADAS 
DECLARAMOS UNA VARIBLE CONST DEL PAQUETE 
Y ASI PODER HACE RUNA CONCATENACION DE COMANDOS PARA USARLOS 
AL MONENTO DE METER DATOS DESDE LA CONSOLA DE COMANDO
.COMAND=> ME SIRVE PARA 
1- HACER LA GUIA DE AYUDA DE MI PALICACION CON EL --HELP
2- ASIGNAR LAS PALABRAS CLAVES
3- EL PRIMER PARAMETRO ES EL COMANDO O NOMBRE DEL COMANDO QUE DESEAMOS COLOCAR
4- EL SEGUNDO PARAMETRO ES UN MSN DE INFORMCION
5- EL TERCER PARAMETRO ES UN JSON DONDE PODEMOS COLOCAR UNA SERIE DE PARAMETROS
QUE RECOGERAN VALORES PARA REALIZAR UNA FUNCION
base=> ES EL NOMBRE QUE LE ASIGNE A MI PARAMETRO QUE PARA LLAMARLO DESDE
LA CONSOLA DEBE SER --base Y EL ALIAS ES b QUE PARA LLAMARLO DESDE LA CONSOLA 
ES -b 
demand=> EN TRUE SIGNIFICA QUE ES NECESARIO INTRODUCIRLE ALGUN VALOR 
6- CON EL COMANDO .HELP() SE CREA DE FORMA AUTONOMA UNA BREVE GUIA DE NUESTRA APLICACION */

// hacemos una optimizacion para evitar codigo redundante 

const opt = {
    base: {
        demand: true,
        alias: 'b'
    },
    limite: {
        alias: 'l',
        default: 10
    }
}
const argv = require('yargs')
    .command('listar', 'Listar la tabla de Multiplicar por la consola', opt)
    .command('crear', 'Creacion de la tabla de Multiplicacion', opt)
    .help()
    .argv;

module.exports = {
    argv
}